### ISSUE TITLE
RogueKiller / UCheck : doesn't work anymore

### ISSUE THREAD

**Issue by M0lyk** [ABOATDev/UnlockSoftwares#1]
Already used UnlockSoftwares in the past with success some months ago, with failure since a few weeks

Just updated from 2.0 to 2.1 (Same failure in v2.0)

First the process of the apps RogueKiller / UCheck are killed

Then I click on Activate in the "Adlice Suite" section

In both applications the activate trial button remains without effect

**Comment by FazCodeFR** [comment]
Salut, 
Oui désolé la suite Adlice  ne semble plus activable avec mon logiciel, je m'y suis penché, 

J'ai trouver une méthode manuelle pour roguekiller dernière version (15.1.0.0 64bits) 

Fermer roguekiller 
Désinstaller roguekiller 

Dossier et fichier à supprimé : 
```
C:\ProgramData\RogueKiller
C:\Program Files\RogueKiller
```


Dans le registre supprimé  :
```
Ordinateur\HKEY_CURRENT_USER\SOFTWARE\Adlice Software
Ordinateur\HKEY_USERS\.DEFAULT\Software\Adlice Software
```

relancer l'installation ou le fichier portable roguekiller, dans roguekiller activé la période d'essais 


Cela dois être pareil pour toute la suite, voici la méthode manuelle, qui pourra être implanter dans UnlockSoftwares mais il prendra plus de temps à venir (écrire en code , tester, vérifier, publier ...) 


-------


Hi there, 
Yes sorry the Adlice suite doesn't seem to be activated with my software anymore, I've been looking into it, 

I found a manual method for roguekiller last version (15.1.0.0 64bits) 

Close roguekiller 
Uninstall roguekiller 

Folder and file to remove : 
```
C:\ProgramData\RogueKiller
C:\Program Files\RogueKiller
```


In the deleted registry:
```
Computer\HKEY_CURRENT_USER\SOFTWARE\Adlice Software
Computer\HKEY_USERS\.DEFAULT\Software\Adlice Software\RogueKiller Anti-Malware
```

restart the installation or the roguekiller portable file, in roguekiller activate the test period 


It must be the same for all the rest, here is the manual method, which could be implemented in UnlockSoftwares but it will take more time to come (write in code, test, check, publish ...) 


Thank you for using my software

**Comment by FazCodeFR** [comment]
I fixed the bug !  https://github.com/ABOATDev/UnlockSoftwares/releases
Can you give me some feedback ?
