### ISSUE TITLE
Why so many detections?

### ISSUE THREAD

**Issue by Scrut1ny** [ABOATDev/UnlockSoftwares#3]
https://www.virustotal.com/gui/file/9c0b89e89e23b816f1bdbe8d4a93811347b259f2c3dc139a1b2ec11574204168

**Comment by FazCodeFR** [comment]
### FRANCAIS : 

Malheureusement mon logiciel est bloqué par la plupart des anti-virus

Je vous rassure c'est du faux-positif.


Pourquoi est t'il détecté par les Anti-Virus ?
> Définition faux-positif : Un faux positif est une erreur de jugement d'un programme de détection, qui va réagir alors qu'il n'y a pas lieu de le faire.


Voici la liste du pourquoi mon logiciel est détecté :

- Il va chercher des scripts sur internet  [Dans le code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788) [Dans le code ex2](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788)

- Il possède de nombreux Button vers les liens de téléchargement OFFICIEL des logiciels [Dans le code](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L103)  [Screen1](https://prnt.sc/4oUln9ldwgYt) [Screen2](https://prnt.sc/ba6l_W0vxhs3)
- Modifie, supprimer ou rajoute des clés au registres.[ Dans le code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1595)
- Modifie le fichier Host. [Dans le code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1707)
- Modifie l'état d'un fichier (caché, lecture seul ...) [Dans le code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788)
- Télécharge le fichier Eicar pour test l'AV. [C'est quoi ? ]( https://en.wikipedia.org/wiki/EICAR_test_file) [Dans le code ?](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L103)
- Supprime tout un répertoire en mode forcé. [Dans le code](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788)



Permet d'avoir plein de raccourci utile windows : WindowsRaccourci.rar
[Dans le projet ](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Resources/WindowsRaccourci.rar)
[VT](https://www.virustotal.com/gui/file/d8987f0e168129fa362aa6166cbbf3ffcb17246ecbce5e4754a24c75961a758d) : 1 / 56
C'est uniquement des fichier raccourci windows (shortcut (LNK) files.) .....


Affiche la promotion du jour du site https://www.giveawayoftheday.com/  : GiveAwayOfTheDay.vbs
[Dans le projet](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Resources/GiveAwayOfTheDay.vbs) 
[VT](https://www.virustotal.com/gui/file/8b4a6d074a6e89734f8492bb01410fb595b7a0b56c74d8029d450951cbbc4369) :  2 / 59

La plupart des fonctionnées détecter par les anti-virus n'est pas essentiel au projet et peu donc être enlever 


### ENGLISH : 



Unfortunately my software is blocked by most anti-virus software

Je vous rassure c'est du faux-positif.
Why is it detected by Anti-Virus software?

> False positive definition: A false positive is an error in judgement by a detection programme, which will react when it should not.

Here is the list of why my software is detected:

- It fetches scripts from internet [In the code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788) [In the code ex2](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788)

- It has many buttons to the OFFICIAL software download links [In the code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L103)  [Screen1](https://prnt.sc/4oUln9ldwgYt) [Screen2](https://prnt.sc/ba6l_W0vxhs3)
- Modify, delete or add keys to the registry [ =In the code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1595)
- Modify the Host file. [In the code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1707)
- Change the state of a file (hidden, read-only ...) [In the code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788)
- Download the Eicar file to test the AV [What is it ? ]( https://en.wikipedia.org/wiki/EICAR_test_file) [In the code ex ](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L103)
- Deletes an entire directory in forced mode. [In the code ex](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Form1.vb#L1788)



Allows you to have lots of useful windows shortcuts  : WindowsRaccourci.rar
[In the project](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Resources/WindowsRaccourci.rar)
[VT](https://www.virustotal.com/gui/file/d8987f0e168129fa362aa6166cbbf3ffcb17246ecbce5e4754a24c75961a758d) : 1 / 56
It is only windows shortcut (LNK) files. .....


Displays the site's daily software promotion https://www.giveawayoftheday.com/  : GiveAwayOfTheDay.vbs
[In the project](https://github.com/ABOATDev/UnlockSoftwares/blob/main/UnlockSoftwares/Resources/GiveAwayOfTheDay.vbs) 
[VT](https://www.virustotal.com/gui/file/8b4a6d074a6e89734f8492bb01410fb595b7a0b56c74d8029d450951cbbc4369) :  2 / 59

Most of the features detected by anti-virus software are not essential to the project and can therefore be removed

**Comment by Scrut1ny** [comment]
I understand, I trust the program now. I read through the source code & saw for my self, cool little project by the way. ❤️
